# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_manager_filter.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_DataManagerFilter(object):
    def setupUi(self, DataManagerFilter):
        DataManagerFilter.setObjectName("DataManagerFilter")
        DataManagerFilter.resize(429, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(DataManagerFilter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(DataManagerFilter)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.instrument = QtWidgets.QLineEdit(self.widget)
        self.instrument.setEnabled(False)
        self.instrument.setObjectName("instrument")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.instrument)
        self.source = QtWidgets.QLineEdit(self.widget)
        self.source.setEnabled(False)
        self.source.setObjectName("source")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.source)
        self.provider = QtWidgets.QLineEdit(self.widget)
        self.provider.setEnabled(False)
        self.provider.setObjectName("provider")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.provider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.from_time = QtWidgets.QDateTimeEdit(self.widget)
        self.from_time.setEnabled(False)
        self.from_time.setObjectName("from_time")
        self.horizontalLayout.addWidget(self.from_time)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.to_time = QtWidgets.QDateTimeEdit(self.widget)
        self.to_time.setEnabled(False)
        self.to_time.setObjectName("to_time")
        self.horizontalLayout.addWidget(self.to_time)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.from_wave = QtWidgets.QDoubleSpinBox(self.widget)
        self.from_wave.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_wave.sizePolicy().hasHeightForWidth())
        self.from_wave.setSizePolicy(sizePolicy)
        self.from_wave.setMaximum(10000.0)
        self.from_wave.setObjectName("from_wave")
        self.horizontalLayout_2.addWidget(self.from_wave)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.to_wave = QtWidgets.QDoubleSpinBox(self.widget)
        self.to_wave.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_wave.sizePolicy().hasHeightForWidth())
        self.to_wave.setSizePolicy(sizePolicy)
        self.to_wave.setMaximum(10000.0)
        self.to_wave.setObjectName("to_wave")
        self.horizontalLayout_2.addWidget(self.to_wave)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.starred = QtWidgets.QCheckBox(self.widget)
        self.starred.setEnabled(False)
        self.starred.setText("")
        self.starred.setObjectName("starred")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.starred)
        self.instrument_check = QtWidgets.QCheckBox(self.widget)
        self.instrument_check.setObjectName("instrument_check")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.instrument_check)
        self.source_check = QtWidgets.QCheckBox(self.widget)
        self.source_check.setObjectName("source_check")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.source_check)
        self.provider_check = QtWidgets.QCheckBox(self.widget)
        self.provider_check.setObjectName("provider_check")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.provider_check)
        self.time_check = QtWidgets.QCheckBox(self.widget)
        self.time_check.setObjectName("time_check")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.time_check)
        self.wave_check = QtWidgets.QCheckBox(self.widget)
        self.wave_check.setObjectName("wave_check")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.wave_check)
        self.starred_check = QtWidgets.QCheckBox(self.widget)
        self.starred_check.setObjectName("starred_check")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.starred_check)
        self.physobs_check = QtWidgets.QCheckBox(self.widget)
        self.physobs_check.setObjectName("physobs_check")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.physobs_check)
        self.physobs = QtWidgets.QLineEdit(self.widget)
        self.physobs.setEnabled(False)
        self.physobs.setObjectName("physobs")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.physobs)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(DataManagerFilter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DataManagerFilter)
        self.buttonBox.accepted.connect(DataManagerFilter.accept)
        self.buttonBox.rejected.connect(DataManagerFilter.reject)
        self.instrument_check.toggled['bool'].connect(self.instrument.setEnabled)
        self.source_check.toggled['bool'].connect(self.source.setEnabled)
        self.provider_check.toggled['bool'].connect(self.provider.setEnabled)
        self.time_check.toggled['bool'].connect(self.from_time.setEnabled)
        self.time_check.toggled['bool'].connect(self.to_time.setEnabled)
        self.wave_check.toggled['bool'].connect(self.from_wave.setEnabled)
        self.wave_check.toggled['bool'].connect(self.to_wave.setEnabled)
        self.starred_check.toggled['bool'].connect(self.starred.setEnabled)
        self.physobs_check.toggled['bool'].connect(self.physobs.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DataManagerFilter)

    def retranslateUi(self, DataManagerFilter):
        _translate = QtCore.QCoreApplication.translate
        DataManagerFilter.setWindowTitle(_translate("DataManagerFilter", "Dialog"))
        self.from_time.setDisplayFormat(_translate("DataManagerFilter", "yyyy-MM-dd hh:mm"))
        self.label_5.setText(_translate("DataManagerFilter", "-"))
        self.to_time.setDisplayFormat(_translate("DataManagerFilter", "yyyy-MM-dd hh:mm"))
        self.label_7.setText(_translate("DataManagerFilter", "-"))
        self.instrument_check.setText(_translate("DataManagerFilter", "Instrument:"))
        self.source_check.setText(_translate("DataManagerFilter", "Source:"))
        self.provider_check.setText(_translate("DataManagerFilter", "Provider:"))
        self.time_check.setText(_translate("DataManagerFilter", "Time:"))
        self.wave_check.setText(_translate("DataManagerFilter", "Wavelength:"))
        self.starred_check.setText(_translate("DataManagerFilter", "Starred:"))
        self.physobs_check.setText(_translate("DataManagerFilter", "Physical Observable:"))
