# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_event.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DownloadEvent(object):
    def setupUi(self, DownloadEvent):
        DownloadEvent.setObjectName("DownloadEvent")
        DownloadEvent.resize(440, 733)
        self.verticalLayout = QtWidgets.QVBoxLayout(DownloadEvent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_box = QtWidgets.QFrame(DownloadEvent)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.message_box.setPalette(palette)
        self.message_box.setAutoFillBackground(True)
        self.message_box.setFrameShape(QtWidgets.QFrame.Panel)
        self.message_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message_box.setObjectName("message_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.message_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.message_label = QtWidgets.QLabel(self.message_box)
        self.message_label.setObjectName("message_label")
        self.horizontalLayout_3.addWidget(self.message_label)
        self.close_button = QtWidgets.QToolButton(self.message_box)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_3.addWidget(self.close_button)
        self.verticalLayout.addWidget(self.message_box)
        self.groupBox = QtWidgets.QGroupBox(DownloadEvent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.from_date = QtWidgets.QDateTimeEdit(self.widget_2)
        self.from_date.setObjectName("from_date")
        self.horizontalLayout_2.addWidget(self.from_date)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.to_date = QtWidgets.QDateTimeEdit(self.widget_2)
        self.to_date.setObjectName("to_date")
        self.horizontalLayout_2.addWidget(self.to_date)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widget_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.event_type = QtWidgets.QComboBox(self.groupBox)
        self.event_type.setObjectName("event_type")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.event_type)
        self.verticalLayout.addWidget(self.groupBox)
        self.widget_3 = QtWidgets.QWidget(DownloadEvent)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.search_button = QtWidgets.QPushButton(self.widget_3)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_4.addWidget(self.search_button)
        self.verticalLayout.addWidget(self.widget_3)
        self.table = QtWidgets.QTableWidget(DownloadEvent)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.table)
        self.widget = QtWidgets.QWidget(DownloadEvent)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.query_button = QtWidgets.QPushButton(self.widget)
        self.query_button.setAutoDefault(True)
        self.query_button.setDefault(True)
        self.query_button.setObjectName("query_button")
        self.horizontalLayout.addWidget(self.query_button)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(DownloadEvent)
        self.close_button.clicked.connect(self.message_box.hide)
        QtCore.QMetaObject.connectSlotsByName(DownloadEvent)

    def retranslateUi(self, DownloadEvent):
        _translate = QtCore.QCoreApplication.translate
        DownloadEvent.setWindowTitle(_translate("DownloadEvent", "Form"))
        self.message_label.setText(_translate("DownloadEvent", "ERROR Message"))
        self.close_button.setText(_translate("DownloadEvent", "X"))
        self.groupBox.setTitle(_translate("DownloadEvent", "Filter"))
        self.label.setText(_translate("DownloadEvent", "Time Range:"))
        self.from_date.setDisplayFormat(_translate("DownloadEvent", "yyyy-MM-dd hh:mm"))
        self.label_2.setText(_translate("DownloadEvent", "-"))
        self.to_date.setDisplayFormat(_translate("DownloadEvent", "yyyy-MM-dd hh:mm"))
        self.label_3.setText(_translate("DownloadEvent", "Event Type:"))
        self.search_button.setText(_translate("DownloadEvent", "Search"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("DownloadEvent", "Type"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("DownloadEvent", "Start Time"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("DownloadEvent", "End Time"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("DownloadEvent", "Location"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("DownloadEvent", "Observatory"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("DownloadEvent", "Channel"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("DownloadEvent", "FRM"))
        self.query_button.setText(_translate("DownloadEvent", "Query"))

